// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfwhqegmusvpksmutkap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmd2hxZWdtdXN2cGtzbXV0a2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTEzMTksImV4cCI6MjA2OTM4NzMxOX0.noyFLzNlhS4aasajlFcdZckgU1ciubcDnC2gQxxcGeY";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});